modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="cowsimulator" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cow Simulator" #mandatory
logoFile="cowsim.png" #optional
credits="" #optional
authors="Absolem Jackdaw" #optional
description='''
Live the cow life!
'''
[[dependencies.cowsimulator]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.cowsimulator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
